### ISSUE TITLE
Adding additional ssDNA between sides of helix bundles?

### ISSUE THREAD

**Issue by WillTKaufhold** [cmhuang2011/MagicDNA#1]
Hi Chao-Min -- wondered if you were planning to add support for adding ssDNA between scaffold connections which don't start and end on the termini of helix bundles? 

I see at the moment that ssDNA connections which don't both start and end on helix bundles are marked "non-changable", and are color coded black, with number of ssDNAs stuck at 0. While I can change this manually in Cadnano by altering the scaffold routing, I can't then import my changed .json file back into MagicDNA which I need for oxDNA output. 

If you let me know either way it would be great. If you don't have any plans to add this feature, I'll try myself. The software is awesome and we've successfully folded a wacky origami designed by MagicDNA. Thanks!

**Comment by cmhuang2011** [comment]
> Hi Chao-Min -- wondered if you were planning to add support for adding ssDNA between scaffold connections which don't start and end on the termini of helix bundles?
> 
> I see at the moment that ssDNA connections which don't both start and end on helix bundles are marked "non-changable", and are color coded black, with number of ssDNAs stuck at 0. While I can change this manually in Cadnano by altering the scaffold routing, I can't then import my changed .json file back into MagicDNA which I need for oxDNA output.
> 
> If you let me know either way it would be great. If you don't have any plans to add this feature, I'll try myself. The software is awesome and we've successfully folded a wacky origami designed by MagicDNA. Thanks!

**Comment by cmhuang2011** [comment]
Hi Will, 

 Thanks for using MagicDNA. I am not so familiar with answering questions on Github. Hence, if I accidentally close your reporting issue, please forgive me. 

In MagicDNA, ssDNA on scaffold is achieved by extending scaffold to either end on bundles. I believe you may have noticed that by observing exported caDNAno JSON files. The challenges to achieve your request is the consideration of the ability to export that to caDNAno. However, you can insert a very short bundle (~2 bps, preferred 2HB in honeycomb) as an intermediate bundle between the two bundles which you originally plan to connect. Then in ssDNA GUI, the single-stranded values will be interpreted as extending scaffold on this intermediate bundle. Due to this intermediate bundle default to be 2bps double-stranded cylinder model, you can either delete the staple portion in caDNAno (should be very short) on this bundle or I can tell you how to modify the code to automatically ignore staples shorter than a certain value (ex. 5 nt). 

Also, if the modification in caDNAno involves creating new cylinders or re-numbering , this will create errors when importing to MagicDNA. 

I hope this is helpful for your future design. I prefer to answer any MagicDNA related question by my email (huang.2011@osu.edu) or we have a Slack channel for all MagicDNA users, where I can notice questions easily and quickly. Questions on Github are still welcome. But we want to gather all the questions together.

Best,
Chao-Min

**Comment by WillTKaufhold** [comment]
Thanks Chao-Min!
